"""Added month and year column to note

Revision ID: 4e369d7052c1
Revises: d058644af300
Create Date: 2026-05-01 09:10:56.763476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e369d7052c1'
down_revision: Union[str, Sequence[str], None] = 'd058644af300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'year')
    op.drop_column('notes', 'month')
    # ### end Alembic commands ###
