"""Made month and year not nullable in notes table 

Revision ID: f40276450ae1
Revises: 4e369d7052c1
Create Date: 2026-05-01 09:19:12.658156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40276450ae1'
down_revision: Union[str, Sequence[str], None] = '4e369d7052c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notes', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notes', 'month',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
